packages:
  - apps/*
  - configs/*
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - prisma
