#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running pre-commit checks..."

echo "📝 Checking format..."
pnpm format

echo "🔍 Running lint..."
pnpm lint

echo "✅ Pre-commit checks completed!"